repos:
  - repo: local
    hooks:
      - id: spotless-apply
        name: Run Spotless Apply
        entry: ./gradlew spotlessApply
        language: system
        always_run: true
        pass_filenames: false
