name: Slack - Issue Closed

on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK_URL:
        required: true
      REPOSITORY_TOKEN:
        required: true

jobs:
  send-slack:
    runs-on: ubuntu-latest

    steps:
      - name: Extract issue info and linked PRs
        id: issue-info
        env:
          REPOSITORY_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}
        run: |
          set -e

          REPO="${{ github.repository }}"
          REPO_OWNER=$(echo "$REPO" | cut -d'/' -f1)
          REPO_NAME=$(echo "$REPO" | cut -d'/' -f2)
          ISSUE_NUMBER=$(jq -r '.issue.number' "$GITHUB_EVENT_PATH")
          ISSUE_TITLE=$(jq -r '.issue.title' "$GITHUB_EVENT_PATH")
          ISSUE_URL=$(jq -r '.issue.html_url' "$GITHUB_EVENT_PATH")
          ISSUE_USER=$(jq -r '.issue.user.login' "$GITHUB_EVENT_PATH")
          ISSUE_USER_AVATAR=$(jq -r '.issue.user.avatar_url' "$GITHUB_EVENT_PATH")

          echo "🔍 이슈 번호: $ISSUE_NUMBER"
          echo "🔍 이슈 제목: $ISSUE_TITLE"
          echo "🔍 레포지토리: $REPO_OWNER/$REPO_NAME"

          GRAPHQL_STRING='query($owner: String!, $name: String!, $number: Int!) {
            repository(owner: $owner, name: $name) {
              issue(number: $number) {
                timelineItems(itemTypes: [CONNECTED_EVENT], first: 100) {
                  nodes {
                    ... on ConnectedEvent {
                      subject {
                        ... on PullRequest {
                          number
                          title
                          url
                        }
                      }
                    }
                  }
                }
              }
            }
          }'

          GRAPHQL_QUERY=$(jq -n \
            --arg query "$GRAPHQL_STRING" \
            --arg owner "$REPO_OWNER" \
            --arg name "$REPO_NAME" \
            --argjson number "$ISSUE_NUMBER" \
            '{
              query: $query,
              variables: {
                owner: $owner,
                name: $name,
                number: $number
              }
            }')

          RESPONSE_GRAPHQL=$(curl -s -X POST https://api.github.com/graphql \
            -H "Authorization: Bearer $REPOSITORY_TOKEN" \
            -H "Content-Type: application/json" \
            -d "$GRAPHQL_QUERY")

          echo "🧪 GraphQL 응답: $(echo "$RESPONSE_GRAPHQL" | jq -c '.')"

          PRS_GRAPHQL=$(echo "$RESPONSE_GRAPHQL" | jq -r '
            .data.repository.issue.timelineItems.nodes[]
            | select(.subject != null)
            | select(.subject.number != null and .subject.title != null and .subject.url != null)
            | "- [#\(.subject.number)](\(.subject.url)) \(.subject.title)"')

          echo "🔗 GraphQL로 찾은 PR:"
          echo "$PRS_GRAPHQL"

          RESPONSE_REST=$(curl -s -H "Authorization: Bearer $REPOSITORY_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${REPO}/issues/${ISSUE_NUMBER}/events")

          echo "🧪 REST 이벤트 응답: $(echo "$RESPONSE_REST" | jq -c '[.[] | select(.event == "cross-referenced")]')"

          PRS_REST=$(echo "$RESPONSE_REST" | jq -r '
            .[]
            | select(.event == "cross-referenced")
            | select(.source.issue.pull_request)
            | "- [#\(.source.issue.number)](\(.source.issue.html_url)) \(.source.issue.title)"')

          echo "🔗 REST로 찾은 PR:"
          echo "$PRS_REST"

          LINKED_PRS=$(printf "%s\n%s" "$PRS_GRAPHQL" "$PRS_REST" | sort | uniq)

          echo "🧩 병합된 최종 PR 목록:"
          echo "$LINKED_PRS"

          if [ -z "$LINKED_PRS" ]; then
            LINKED_PRS="❌ 연결된 PR이 없습니다!"
          fi

          HEADER_TEXT="🗑️ 이슈 종료"
          ISSUE_SECTION="*[<${ISSUE_URL}|#${ISSUE_NUMBER}>]*
          ${ISSUE_TITLE}
          ${LINKED_PRS}"

          echo "✅ 최종 Slack 메시지:"
          echo "$ISSUE_SECTION"

          echo "header_text=$(printf "%s" "$HEADER_TEXT" | jq -Rs .)" >> $GITHUB_OUTPUT
          echo "issue_section=$(printf "%s" "$ISSUE_SECTION" | jq -Rs .)" >> $GITHUB_OUTPUT
          echo "issue_user=${ISSUE_USER}" >> $GITHUB_OUTPUT
          echo "issue_user_avatar=${ISSUE_USER_AVATAR}" >> $GITHUB_OUTPUT

      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v2.1.1
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            blocks:
              - type: "header"
                text:
                  type: "plain_text"
                  text: ${{ steps.issue-info.outputs.header_text }}
                  emoji: true
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: ${{ steps.issue-info.outputs.issue_section }}
                accessory:
                  type: "image"
                  image_url: "${{ steps.issue-info.outputs.issue_user_avatar }}"
                  alt_text: "by ${{ steps.issue-info.outputs.issue_user }}"
              - type: "context"
                elements:
                  - type: "mrkdwn"
                    text: "by <https://github.com/${{ steps.issue-info.outputs.issue_user }}|${{ steps.issue-info.outputs.issue_user }}>"
